export default [
    {
        type: 'datepicker',
        margin: true,
        showLabel: true,
        label: 'From',
        placeholder: 'Date',
        class: 'font-small-3',
        model: null,
        locale: 'en',
        dateFormOptions: { year: 'numeric', month: 'numeric', day: 'numeric' },
        cols: 6
    },
    {
        type: 'datepicker',
        margin: true,
        showLabel: true,
        label: 'To',
        placeholder: 'Date',
        class: 'font-small-3',
        model: null,
        locale: 'en',
        dateFormOptions: { year: 'numeric', month: 'numeric', day: 'numeric' },
        cols: 6
    },
    {
        type: 'select',
        margin: true,
        showLabel: true,
        label: 'CR',
        model: null,
        options: [],
        reduce: 'id',
        seletText: 'label',
        cols: 6,
    },
    {
        type: 'select',
        margin: true,
        showLabel: true,
        label: 'DOCUMENT TYPE',
        model: null,
        options: [],
        reduce: 'id',
        seletText: 'label',
        cols: 6,
    },
    {
        type: 'select',
        margin: true,
        showLabel: true,
        label: 'PROGRAMS',
        model: null,
        options: [],
        reduce: 'id',
        seletText: 'label',
        cols: 12,
    },
    {
        type: 'select',
        margin: true,
        showLabel: true,
        label: 'SOURCE',
        model: null,
        options: [],
        reduce: 'id',
        seletText: 'label',
        cols: 12,
    },
    {
        type: 'select',
        margin: true,
        showLabel: true,
        label: 'OWNER',
        model: null,
        options: [],
        reduce: 'id',
        seletText: 'label',
        cols: 12,
    },
    {
        type: 'select',
        margin: true,
        showLabel: true,
        label: 'TASK',
        model: null,
        options: [],
        reduce: 'id',
        seletText: 'label',
        cols: 6,
    },
    {
        type: 'select',
        margin: true,
        showLabel: true,
        label: 'ST/AD',
        model: null,
        options: [],
        reduce: 'id',
        seletText: 'label',
        cols: 6,
    },
    {
        type: 'select',
        margin: true,
        showLabel: true,
        label: 'STATUS LEAD',
        model: null,
        options: [],
        reduce: 'id',
        seletText: 'label',
        cols: 12,
    },
]