export default [
  {
    type: 'datepicker',
    margin: true,
    showLabel: true,
    label: 'From',
    placeholder: 'Date',
    class: 'font-small-3',
    model: null,
    locale: 'en',
    dateFormatOptions: { year: 'numeric', month: 'numeric', day: 'numeric' },
    cols: 6,
  },
  {
    type: 'datepicker',
    margin: true,
    showLabel: true,
    label: 'To',
    placeholder: 'Date',
    class: 'font-small-3',
    model: null,
    locale: 'en',
    dateFormatOptions: { year: 'numeric', month: 'numeric', day: 'numeric' },
    cols: 6,
  },
  {
    type: 'select',
    margin: true,
    showLabel: true,
    label: 'Status Lead',
    model: null,
    options: [],
    reduce: 'id',
    selectText: 'label',
    cols: 12,
  },
  {
    type: 'select',
    margin: true,
    showLabel: true,
    label: 'Owner',
    model: null,
    options: [],
    reduce: 'value',
    selectText: 'label',
    cols: 7,
  },
  {
    type: 'select',
    margin: true,
    showLabel: true,
    label: 'Status owner',
    model: null,
    options: [],
    reduce: 'value',
    selectText: 'label',
    cols: 5,
    emitEvent: true,
    typeEvent: 'status_owner'
  },
  {
    type: 'select',
    margin: true,
    showLabel: true,
    label: 'Assign To',
    model: null,
    options: [],
    reduce: 'value',
    selectText: 'label',
    cols: 7,
  },
  {
    type: 'select',
    margin: true,
    showLabel: true,
    label: 'Status catcher',
    model: null,
    options: [],
    reduce: 'value',
    selectText: 'label',
    cols: 5,
    emitEvent: true,
    typeEvent: 'status_catcher'
  },
  {
    type: 'select',
    margin: true,
    showLabel: true,
    label: 'CR',
    model: null,
    options: [],
    reduce: 'value',
    selectText: 'label',
    cols: 12,
  },
  {
    type: 'select',
    margin: true,
    showLabel: true,
    label: 'Programs',
    multiple: true,
    model: null,
    options: [],
    reduce: 'id',
    selectText: 'label',
    cols: 12,
  },
  {
    type: 'select',
    margin: true,
    showLabel: true,
    label: 'ST/AD',
    model: null,
    options: [],
    reduce: 'label',
    selectText: 'label',
    cols: 6,
  },
  {
    type: 'select',
    margin: true,
    showLabel: true,
    label: 'Source Name',
    multiple: true,
    model: null,
    options: [],
    reduce: 'id',
    selectText: 'label',
    cols: 6,
  },
  {
    type: 'select',
    margin: true,
    showLabel: true,
    label: 'Type Doc',
    model: null,
    options: [],
    reduce: 'value',
    selectText: 'label',
    cols: 6,
  },
]
